spring:
    mvc:
        view:
            prefix: /WEB-INF/views
            suffix: .jsp
    devtools:
        livereload:
            enabled: true
    jpa:
        show-sql: true
        properties:
            hiberante:
                ddl-auto: validate
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://localhost;databaseName=Board;
        username: sa
        password: rudnf12dnjf
        initialize: true
    jackson:
        serialization:
            indent_output: true
server:
    jsp-servlet:
        init-parameters:
            development: true
    port: 80
    context-path: /

logging:
    level:
        root: info
    package: com.general
    path: ../.log
    name: board
    pattern:
        console: "%d{hh:mm:ss} %-5level [%thread] %logger : %msg%n"
---
# ZILET
spring:
    profiles: zilet
server:
    port: 8081
    context-path: /
logging:
    path: ../.log/log.txt
    level:
        com.general.controller: debug
#        org.springframework.security: error
---
# HOME
spring:
    profiles: home
    datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://localhost;databaseName=Board;
        username: sa
        password: rudnf12dnjf
    output:
        ansi:
            enabled: always
server:
    port: 8080
    context-path: /
logging:
    level:
        com.general.controller: debug
        org.springframework.security: debug
---
# RELEASE
spring:
    profiles: release
logging:
    path: D:/web/springbootBoard/.log
